package org.apache.cayenne.examples.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Auto was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Auto extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String AUTO_KEY_PK_COLUMN = "auto_key";


}
