package org.apache.cayenne.examples.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.examples.Auto;
import org.apache.cayenne.examples.Auto2;
import org.apache.cayenne.exp.Property;

/**
 * Class _Composite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Composite extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String K1_PK_COLUMN = "k1";
    public static final String K2_PK_COLUMN = "k2";

    public static final Property<Integer> O = new Property<Integer>("o");
    public static final Property<Auto> AUTO1 = new Property<Auto>("auto1");
    public static final Property<Auto2> AUTO2 = new Property<Auto2>("auto2");

    public void setO(int o) {
        writeProperty("o", o);
    }
    public int getO() {
        Object value = readProperty("o");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAuto1(Auto auto1) {
        setToOneTarget("auto1", auto1, true);
    }

    public Auto getAuto1() {
        return (Auto)readProperty("auto1");
    }


    public void setAuto2(Auto2 auto2) {
        setToOneTarget("auto2", auto2, true);
    }

    public Auto2 getAuto2() {
        return (Auto2)readProperty("auto2");
    }


}
