package org.apache.cayenne.examples.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.examples.Auto;
import org.apache.cayenne.exp.Property;

/**
 * Class _Composite was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Composite extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String K1_PK_COLUMN = "k1";
    public static final String K2_PK_COLUMN = "k2";

    public static final Property<Integer> O = new Property<Integer>("o");
    public static final Property<List<Auto>> AUTO1 = new Property<List<Auto>>("auto1");
    public static final Property<List<Auto>> AUTO2 = new Property<List<Auto>>("auto2");

    public void setO(int o) {
        writeProperty("o", o);
    }
    public int getO() {
        Object value = readProperty("o");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToAuto1(Auto obj) {
        addToManyTarget("auto1", obj, true);
    }
    public void removeFromAuto1(Auto obj) {
        removeToManyTarget("auto1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Auto> getAuto1() {
        return (List<Auto>)readProperty("auto1");
    }


    public void addToAuto2(Auto obj) {
        addToManyTarget("auto2", obj, true);
    }
    public void removeFromAuto2(Auto obj) {
        removeToManyTarget("auto2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Auto> getAuto2() {
        return (List<Auto>)readProperty("auto2");
    }


}
