package org.apache.cayenne.examples.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Dummy was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Dummy extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DUMMY_PK_COLUMN = "dummy";

    public static final Property<String> DUMMY = new Property<String>("dummy");

    public void setDummy(String dummy) {
        writeProperty("dummy", dummy);
    }
    public String getDummy() {
        return (String)readProperty("dummy");
    }

}
